version: '3.8'

services:
  # Test database for isolated testing
  test-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=dreamango_test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d dreamango_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend testing service
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dreamango-backend-test
    environment:
      - DREAMANGO_SECRET_KEY=test-secret-key
      - DREAMANGO_ENV=testing
      - DREAMANGO_DEBUG=True
      - DATABASE_URL=postgresql://test:test@test-db:5432/dreamango_test
      - ALLOWED_HOSTS=localhost,backend-test
    depends_on:
      test-db:
        condition: service_healthy
    command: ["python", "manage.py", "test", "--verbosity=2"]
    volumes:
      - ./test-logs:/app/test-logs
    profiles: ["test"]

  # Frontend testing service  
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    container_name: dreamango-frontend-test
    environment:
      - CI=true
      - BACKEND_URL=http://backend-test:8000
    volumes:
      - ./test-logs:/app/test-logs
    profiles: ["test"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dreamango-backend
    ports:
      - "8000:8000"
    environment:
      - DREAMANGO_SECRET_KEY=${DREAMANGO_SECRET_KEY}
      - DREAMANGO_ENV=${DREAMANGO_ENV:-production}
      - DREAMANGO_DEBUG=${DREAMANGO_DEBUG:-False}
      - DREAMANGO_API_URL=${DREAMANGO_API_URL}
      - DREAMANGO_CORS_ALLOWED_ORIGINS=${DREAMANGO_CORS_ALLOWED_ORIGINS}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_REGION=${GCP_REGION}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:/tmp/gcp-credentials.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dreamango-frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=${DREAMANGO_API_URL}
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
