version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dreamango-backend
    ports:
      - "8000:8000"
    environment:
      - DREAMANGO_SECRET_KEY=${DREAMANGO_SECRET_KEY}
      - DREAMANGO_ENV=${DREAMANGO_ENV:-production}
      - DREAMANGO_DEBUG=${DREAMANGO_DEBUG:-False}
      - DREAMANGO_API_URL=${DREAMANGO_API_URL}
      - DREAMANGO_CORS_ALLOWED_ORIGINS=${DREAMANGO_CORS_ALLOWED_ORIGINS}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_REGION=${GCP_REGION}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:/tmp/gcp-credentials.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dreamango-frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=${DREAMANGO_API_URL}
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
