services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dreamango-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:/tmp/gcp-credentials.json:ro
    environment:
      - DJANGO_SECRET_KEY=your_development_secret_key
      - DATABASE_URL=sqlite:////app/db.sqlite3
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DEBUG=True
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json
      - GCP_PROJECT_ID
      - GCP_REGION
      - CORS_ALLOWED_ORIGINS=http://localhost:5175

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dreamango-frontend
    ports:
      - "5175:5175"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
